variables:
  CI_NAME: "GitLab CI"
  CI_TMP_DIR: "${CI_PROJECT_DIR}.tmp"
  PULL_REQUEST: "true"  # Not sure how to tell MR builds vs. anything else

"METADATA":
  image: amazonlinux:latest
  tags:
    - docker-ci
    - linux
    - amd64
  before_script:
    - yum install -y -q git find xargs sed
    # Grant access to registered private packages
    - REGEX="s;https://gitlab.invenia.ca/;https://gitlab-ci-token:$CI_BUILD_TOKEN@gitlab.invenia.ca/;"
    - find "$CI_PROJECT_DIR" -maxdepth 2 -name url | xargs sed -i -e "$REGEX"
    # If any success files exist, remove them
    - "[ -e $CI_TMP_DIR/success-* ] && rm $CI_TMP_DIR/success-*"
  script:
    - sh .test/check-https.sh gitlab.invenia.ca
    - sh .test/ci.sh
